FROM ubuntu:16.04
RUN apt-get update && apt-get install -y \
    build-essential \
    clang \
    clang-format \
    clang-tidy \
    cmake \
    doxygen \
    graphviz \
    lcov \
    libpoco-dev \
    valgrind \
    libeigen3-dev
