FROM ubuntu:16.04
RUN apt-get update && apt-get install -y \
    build-essential \
    clang-6.0 \
    clang-format-6.0 \
    clang-tidy-6.0 \
    cmake \
    doxygen \
    graphviz \
    lcov \
    libpoco-dev \
    valgrind \
    libeigen3-dev \
    && rm -rf /var/lib/apt/lists/*
